### ISSUE TITLE
Issue with DB

### ISSUE THREAD

**Issue by JJImenezna** [lazariv/easybuild-easyconfigs#1]
Hello

I get this error launching rserver.  
Any help will be really apreciated.

[rserver] ERROR database error 7 (Cannot establish connection to the database. unable to open database file); OCCURRED AT rstudio::core::Error rstudio::core::database::ConnectVisitor::operator()(const rstudio::core::database::SqliteConnectionOptions&) const src/cpp/core/Database.cpp:176; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:694

Many thanks in advance
Regards

**Comment by JJImenezna** [comment]
Hello
Update

Sanity cheack wass supossed to be fine however tha app was not being launched.
I uncommented the lines for sqllite in .../../RStudio-Server/1.4.1717-foss-2021a-Java-11-R-4.1.0/extras/conf/database.conf
and after changing permissions the database is created automaticallly ( at leat for sqlite)
I guess this location must be exported in order all clients are able lo launch the app however NFS is not recommended for this db. I will update the loop just in case someone finds it useful.

Best Regards

**Comment by lazariv** [comment]
I have never had similar issues, even with multiple users on an HPC machine.
